; PlatformIO Project Configuration File
; Supports both ESP8266 (NodeMCU) and Arduino Nano V3

[env]
monitor_speed = 115200 

[platformio]
src_dir=.

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -DARDUINO_ARCH_AVR
